const { SHARED } = require("./content");

function json(value) {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function indent(value, count) {
  const prefix = " ".repeat(count);
  return value
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n");
}

function pageShell({ htmlLang, head, body }) {
  const markup = `<!doctype html>
<!-- Generated by scripts/generate.js. Do not edit manually. -->
<html lang="${htmlLang}">

<head>
${head}
</head>

<body>
${body}
</body>

</html>
`;

  return markup
    .split(/(<script\b[\s\S]*?<\/script>)/gi)
    .map((part, index) =>
      index % 2 === 0
        ? part.replace(/&(?!(?:#\d+|#x[\da-f]+|[a-z][\da-z]+);)/gi, "&amp;")
        : part
    )
    .join("");
}

function renderMetaTags({
  title,
  description,
  canonical,
  locale,
  alternateLocale,
  ogImageAlt,
}) {
  return `  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="description" content="${description}" />
  <meta name="author" content="${SHARED.organizationName}" />
  <meta name="robots" content="index, follow, max-image-preview:large" />
  <meta name="theme-color" content="#f5f7fa" />
  <meta name="color-scheme" content="light" />
  <meta name="format-detection" content="telephone=no" />
  <title>${title}</title>
  <link rel="canonical" href="${canonical}" />
  <link rel="alternate" hreflang="en" href="${SHARED.siteUrl}/en/" />
  <link rel="alternate" hreflang="de" href="${SHARED.siteUrl}/de/" />
  <link rel="alternate" hreflang="x-default" href="${SHARED.siteUrl}/" />
  <meta property="og:title" content="${title}" />
  <meta property="og:description" content="${description}" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${canonical}" />
  <meta property="og:image" content="${SHARED.socialImageUrl}" />
  <meta property="og:image:secure_url" content="${SHARED.socialImageUrl}" />
  <meta property="og:image:type" content="image/jpeg" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="${ogImageAlt}" />
  <meta property="og:site_name" content="Paluv" />
  <meta property="og:locale" content="${locale}" />
  <meta property="og:locale:alternate" content="${alternateLocale}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${title}" />
  <meta name="twitter:description" content="${description}" />
  <meta name="twitter:image" content="${SHARED.socialImageUrl}" />
  <meta name="twitter:image:alt" content="${ogImageAlt}" />
  <link rel="icon" href="/assets/paluvico.ico" sizes="any" />
  <link rel="preload" href="${SHARED.heroImage}" as="image" type="image/webp" fetchpriority="high" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="${SHARED.fontsHref}" rel="stylesheet" />
  <link rel="stylesheet" href="/css/styles.css?v=${SHARED.assetVersion}" />
  <script>
    document.documentElement.classList.add("js-enabled");
    window.__paluvRevealFallback = window.setTimeout(function () {
      document.documentElement.classList.add("reveal-fallback");
    }, 2500);
  </script>
  <script defer src="${SHARED.analyticsScript}"></script>`;
}

function renderHomepageHead(localeContent, localeKey) {
  const canonical = `${SHARED.siteUrl}/${localeKey}/`;
  const graph = [
    {
      "@type": "Organization",
      "@id": `${SHARED.siteUrl}/#organization`,
      name: SHARED.organizationName,
      alternateName: "Paluv",
      url: `${SHARED.siteUrl}/`,
      logo: {
        "@type": "ImageObject",
        url: SHARED.logoUrl,
        width: 420,
        height: 196,
      },
      image: SHARED.socialImageUrl,
      description: localeContent.description,
      email: SHARED.generalEmail,
      areaServed: "Europe",
      knowsAbout: [
        "General aviation",
        "Aviation software",
        "Pilot services",
        "Flight school workflows",
      ],
      contactPoint: [
        {
          "@type": "ContactPoint",
          email: SHARED.generalEmail,
          contactType: "customer support",
          availableLanguage: ["German", "English"],
        },
        {
          "@type": "ContactPoint",
          email: SHARED.businessEmail,
          contactType: "business inquiries",
          availableLanguage: ["German", "English"],
        },
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SHARED.siteUrl}/#website`,
      url: `${SHARED.siteUrl}/`,
      name: "Paluv",
      publisher: { "@id": `${SHARED.siteUrl}/#organization` },
      inLanguage: ["de", "en"],
    },
    {
      "@type": "WebPage",
      "@id": `${canonical}#webpage`,
      url: canonical,
      name: localeContent.title,
      description: localeContent.description,
      isPartOf: { "@id": `${SHARED.siteUrl}/#website` },
      about: { "@id": `${SHARED.siteUrl}/#organization` },
      primaryImageOfPage: {
        "@type": "ImageObject",
        url: SHARED.socialImageUrl,
        width: 1200,
        height: 630,
      },
      inLanguage: localeContent.htmlLang,
    },
    ...localeContent.products.map((product) => ({
      "@type": "Product",
      name: product.title,
      description: product.description,
      image: `${SHARED.siteUrl}${product.image}`,
      url: product.href,
      brand: { "@id": `${SHARED.siteUrl}/#organization` },
      category: product.tag,
    })),
  ];

  return `${renderMetaTags({
    title: localeContent.title,
    description: localeContent.description,
    canonical,
    locale: localeContent.locale,
    alternateLocale: localeContent.alternateLocale,
    ogImageAlt: localeContent.ogImageAlt,
  })}
  <script type="application/ld+json">
${indent(json({ "@context": "https://schema.org", "@graph": graph }), 4)}
  </script>`;
}

function renderLegalHead(localeKey, localeContent, pageContent) {
  const canonical = `${SHARED.siteUrl}${pageContent.path}`;
  const alternate = `${SHARED.siteUrl}${pageContent.alternatePath}`;

  return `  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="description" content="${pageContent.metaDescription}" />
  <meta name="robots" content="index, follow" />
  <meta name="theme-color" content="#f5f7fa" />
  <meta name="color-scheme" content="light" />
  <title>${pageContent.pageTitle}</title>
  <link rel="canonical" href="${canonical}" />
  <link rel="alternate" hreflang="${localeKey}" href="${canonical}" />
  <link rel="alternate" hreflang="${localeKey === "en" ? "de" : "en"}" href="${alternate}" />
  <link rel="alternate" hreflang="x-default" href="${localeKey === "en" ? canonical : alternate}" />
  <meta property="og:title" content="${pageContent.pageTitle}" />
  <meta property="og:description" content="${pageContent.metaDescription}" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${canonical}" />
  <meta property="og:site_name" content="Paluv" />
  <link rel="icon" href="/assets/paluvico.ico" sizes="any" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="${SHARED.fontsHref}" rel="stylesheet" />
  <link rel="stylesheet" href="/css/styles.css?v=${SHARED.assetVersion}" />
  <script src="/js/scripts.js?v=${SHARED.assetVersion}" defer></script>`;
}

function renderHeader(localeKey, localeContent) {
  const alternatePath = localeKey === "en" ? "/de/" : "/en/";

  return `    <header class="site-header" data-site-header>
      <a class="brand" href="/${localeKey}/" aria-label="Paluv home">
        <img class="brand-logo" src="/assets/paluvlogo.png" width="420" height="196" alt="Paluv" />
      </a>
      <nav class="site-nav" id="site-nav" aria-label="${localeKey === "de" ? "Hauptnavigation" : "Main navigation"}">
        <a href="#products">${localeContent.nav.products}</a>
        <a href="#services">${localeContent.nav.services}</a>
        <a href="#partners">${localeContent.nav.partners}</a>
        <a href="#contact">${localeContent.nav.contact}</a>
      </nav>
      <div class="header-actions">
        <a class="language-switch" href="${alternatePath}" data-language-link
          lang="${localeKey === "en" ? "de" : "en"}" hreflang="${localeKey === "en" ? "de" : "en"}"
          aria-label="${localeContent.nav.languageSwitch}">
          <span>${localeKey.toUpperCase()}</span>
          <span aria-hidden="true">→</span>
          <strong>${localeKey === "en" ? "DE" : "EN"}</strong>
        </a>
        <a class="button button--small header-cta" href="#contact">${localeContent.hero.primaryCta}</a>
        <button class="nav-toggle" type="button" aria-controls="site-nav" aria-expanded="false"
          aria-label="${localeContent.nav.menu}">
          <span></span><span></span>
        </button>
      </div>
    </header>`;
}

function renderHero(localeContent) {
  const metaMarkup = localeContent.hero.meta
    .map(
      (item) => `          <div>
            <dt>${item.label}</dt>
            <dd>${item.value}</dd>
          </div>`
    )
    .join("\n");

  return `      <section class="hero" id="top" aria-labelledby="hero-title">
        <div class="hero-copy">
          <p class="eyebrow">${localeContent.hero.eyebrow}</p>
          <h1 id="hero-title">${localeContent.hero.title}</h1>
          <p class="hero-subtitle">${localeContent.hero.subtitle}</p>
          <div class="hero-actions">
            <a class="button" href="#contact">${localeContent.hero.primaryCta}<span aria-hidden="true">↗</span></a>
            <a class="text-link" href="#products">${localeContent.hero.secondaryCta}<span aria-hidden="true">↓</span></a>
          </div>
        </div>
        <div class="hero-visual is-visible">
          <img src="${SHARED.heroImage}" width="1693" height="929"
            alt="${localeContent.ogImageAlt}" fetchpriority="high" decoding="async" />
          <div class="hero-visual__wash" aria-hidden="true"></div>
          <div class="hero-visual__label">
            <span>EDRY</span>
            <strong>${localeContent.map.title}</strong>
          </div>
          <div class="hero-visual__mark" aria-hidden="true">49°18′N<br />08°27′E</div>
        </div>
        <dl class="hero-meta">
${metaMarkup}
        </dl>
      </section>`;
}

function renderPromise(localeContent) {
  const points = localeContent.promise.points
    .map((point) => `            <li>${point}</li>`)
    .join("\n");

  return `      <section class="promise section reveal" aria-labelledby="promise-title">
        <div>
          <p class="eyebrow eyebrow--light">${localeContent.promise.eyebrow}</p>
          <h2 id="promise-title">${localeContent.promise.title}</h2>
        </div>
        <div class="promise-copy">
          <p>${localeContent.promise.text}</p>
          <ul>
${points}
          </ul>
        </div>
      </section>`;
}

function renderProductCards(items) {
  return items
    .map(
      (item, index) => `          <article class="product-card reveal">
            <a class="product-card__media" href="${item.href}" aria-label="${item.cta}">
              <img src="${item.image}" alt="${item.imageAlt}" loading="lazy" decoding="async"
                width="${index === 0 ? "1248" : "5976"}" height="${index === 0 ? "832" : "3984"}" />
              <span>${item.tag}</span>
            </a>
            <div class="product-card__body">
              <div>
                <p class="product-card__index">0${index + 1} · Paluv product</p>
                <h3>${item.title}</h3>
                <p>${item.description}</p>
              </div>
              <a class="circle-link" href="${item.href}" aria-label="${item.cta}" title="${item.cta}">
                <span aria-hidden="true">↗</span>
              </a>
            </div>
          </article>`
    )
    .join("\n");
}

function renderProductsSection(localeContent) {
  return `      <section class="section section--spacious" id="products" aria-labelledby="products-title">
        <div class="section-heading">
          <p class="eyebrow">Paluv lab</p>
          <h2 id="products-title">${localeContent.sections.products.title}</h2>
          <p>${localeContent.promise.text}</p>
        </div>
        <div class="products-grid">
${renderProductCards(localeContent.products)}
        </div>
      </section>`;
}

function renderServiceCards(items) {
  return items
    .map(
      (item) => `          <article class="service-card reveal">
            <div class="service-card__top">
              <span>${item.index}</span>
              <span aria-hidden="true">↘</span>
            </div>
            <h3>${item.title}</h3>
            <p>${item.description}</p>
            <small>${item.tag}</small>
          </article>`
    )
    .join("\n");
}

function renderServicesSection(localeContent) {
  return `      <section class="section section--spacious services-section" id="services" aria-labelledby="services-title">
        <div class="section-heading section-heading--split">
          <div>
            <p class="eyebrow">${localeKeyFromContent(localeContent) === "de" ? "Was wir umsetzen" : "What we deliver"}</p>
            <h2 id="services-title">${localeContent.sections.services.title}</h2>
          </div>
          <p>${localeContent.sections.services.subtitle}</p>
        </div>
        <div class="services-grid">
${renderServiceCards(localeContent.services)}
        </div>
      </section>`;
}

function renderPartnerIdentity(item) {
  if (item.logo) {
    return `<span class="partner-logo partner-logo--image">
              <img src="${item.logo}" alt="${item.logoAlt || item.name}" loading="lazy" decoding="async" />
            </span>`;
  }

  return `<span class="partner-logo partner-logo--word" aria-label="${item.name}">${item.logoText}</span>`;
}

function renderPartnersSection(localeContent) {
  const items = localeContent.partners.items
    .map((item) => {
      const cardStart = item.href
        ? `<a class="partner-card reveal" href="${item.href}" rel="external">`
        : `<article class="partner-card reveal">`;
      const cardEnd = item.href ? "</a>" : "</article>";

      return `          ${cardStart}
            <div class="partner-card__top">
              <span>${item.status}</span>
              <span aria-hidden="true">${item.href ? "↗" : "•"}</span>
            </div>
            ${renderPartnerIdentity(item)}
            <div class="partner-card__copy">
              <p>${item.category}</p>
              <h3>${item.name}</h3>
              <p>${item.services}</p>
              <small>${item.note}</small>
            </div>
          ${cardEnd}`;
    })
    .join("\n");

  return `      <section class="section section--spacious partners-section" id="partners" aria-labelledby="partners-title">
        <div class="partners-intro">
          <div class="section-heading">
            <p class="eyebrow">${localeContent.partners.kicker}</p>
            <h2 id="partners-title">${localeContent.sections.partners.title}</h2>
            <p>${localeContent.sections.partners.subtitle}</p>
          </div>
          <p>${localeContent.partners.summary}</p>
        </div>
        <div class="partners-grid">
${items}
        </div>
      </section>`;
}

function renderContact(localeKey, localeContent) {
  return `    <section class="contact-section" id="contact" aria-labelledby="contact-title">
      <div class="contact-intro">
        <p class="eyebrow eyebrow--light">${localeContent.contact.eyebrow}</p>
        <h2 id="contact-title">${localeContent.contact.title}</h2>
        <p>${localeContent.contact.subtitle}</p>
        <div class="contact-direct">
          <span>${localeContent.contact.directLabel}</span>
          <a href="mailto:${SHARED.generalEmail}">${localeContent.contact.directCta}<span aria-hidden="true">↗</span></a>
        </div>
      </div>
      <form class="contact-form" id="contact-form"
        data-sending="${localeContent.contact.sending}"
        data-success="${localeContent.contact.success}"
        data-error="${localeContent.contact.error}">
        <div class="form-row">
          <label>
            <span>${localeContent.contact.fields.name}</span>
            <input type="text" name="name" placeholder="${localeContent.contact.placeholders.name}" autocomplete="name" required />
          </label>
          <label>
            <span>${localeContent.contact.fields.email}</span>
            <input type="email" name="email" placeholder="${localeContent.contact.placeholders.email}" autocomplete="email" required />
          </label>
        </div>
        <label>
          <span>${localeContent.contact.fields.message}</span>
          <textarea name="message" rows="4" placeholder="${localeContent.contact.placeholders.message}" required></textarea>
        </label>
        <div class="form-submit">
          <button class="button button--light" type="submit">${localeContent.contact.submit}<span aria-hidden="true">↗</span></button>
          <p class="form-status" id="form-status" role="status" aria-live="polite"></p>
        </div>
      </form>
    </section>

    <section class="location-strip" aria-labelledby="location-title">
      <div>
        <p class="eyebrow">${localeContent.map.eyebrow}</p>
        <h2 id="location-title">${localeContent.map.title}</h2>
      </div>
      <p>${localeContent.map.caption}</p>
      <a class="text-link" href="https://www.openstreetmap.org/?mlat=49.30472&mlon=8.45167#map=15/49.30472/8.45167"
        rel="external">${localeContent.map.link}<span aria-hidden="true">↗</span></a>
    </section>

    <footer class="site-footer">
      <a class="footer-brand" href="/${localeKey}/">
        <img src="/assets/paluvlogo.png" width="420" height="196" alt="Paluv" />
      </a>
      <p>${localeContent.footer.statement}</p>
      <div class="footer-meta">
        <span>© <span id="year">${SHARED.year}</span> ${SHARED.organizationName}</span>
        <span>${SHARED.generalEmail} · ${SHARED.businessEmail}</span>
        <span class="footer-links">
          <a href="${localeKey === "en" ? "/en/imprint/" : "/de/impressum/"}">${localeContent.footer.imprint}</a>
          <a href="${localeKey === "en" ? "/en/privacy/" : "/de/datenschutz/"}">${localeContent.footer.privacy}</a>
        </span>
      </div>
    </footer>`;
}

function renderHomepageBody(localeKey, localeContent) {
  const skipLabel = localeKey === "de" ? "Zum Inhalt springen" : "Skip to content";

  return `  <a class="skip-link" href="#main">${skipLabel}</a>
  <div class="site-shell">
${renderHeader(localeKey, localeContent)}

    <main id="main">
${renderHero(localeContent)}

${renderPromise(localeContent)}

${renderProductsSection(localeContent)}

${renderServicesSection(localeContent)}

${renderPartnersSection(localeContent)}
    </main>

${renderContact(localeKey, localeContent)}
  </div>

  <script src="/js/scripts.js?v=${SHARED.assetVersion}" defer></script>`;
}

function renderLegalHeader(localeKey, nav, pageType) {
  const homePath = localeKey === "en" ? "/en/" : "/de/";
  const pagePath =
    pageType === "imprint"
      ? localeKey === "en"
        ? "/en/imprint/"
        : "/de/impressum/"
      : localeKey === "en"
        ? "/en/privacy/"
        : "/de/datenschutz/";
  const otherPath =
    pageType === "imprint"
      ? localeKey === "en"
        ? "/de/impressum/"
        : "/en/imprint/"
      : localeKey === "en"
        ? "/de/datenschutz/"
        : "/en/privacy/";

  return `  <div class="legal-page">
    <header class="site-header legal-header">
      <a class="brand" href="${homePath}">
        <img class="brand-logo" src="/assets/paluvlogo.png" width="420" height="196" alt="Paluv" />
      </a>
      <nav class="legal-nav" aria-label="${localeKey === "de" ? "Rechtliche Seiten" : "Legal pages"}">
        <a href="${homePath}">${nav.home}</a>
        <a href="${localeKey === "en" ? "/en/imprint/" : "/de/impressum/"}"${pageType === "imprint" ? ' aria-current="page"' : ""}>${nav.imprint}</a>
        <a href="${localeKey === "en" ? "/en/privacy/" : "/de/datenschutz/"}"${pageType === "privacy" ? ' aria-current="page"' : ""}>${nav.privacy}</a>
      </nav>
      <a class="language-switch" href="${otherPath}" data-language-link lang="${localeKey === "en" ? "de" : "en"}"
        hreflang="${localeKey === "en" ? "de" : "en"}" aria-label="${nav.languageSwitch}">
        <span>${localeKey.toUpperCase()}</span><span aria-hidden="true">→</span><strong>${localeKey === "en" ? "DE" : "EN"}</strong>
      </a>
    </header>
    <div class="legal-context"><a href="${homePath}">Paluv</a><span>/</span><span>${pageType === "imprint" ? nav.imprint : nav.privacy}</span></div>`;
}

function renderLegalSections(sections) {
  return sections
    .map((section) => {
      const paragraphs = section.paragraphs
        .map((paragraph) => `        <p>${paragraph}</p>`)
        .join("\n");
      return `      <section>
        <h2>${section.title}</h2>
${paragraphs}
      </section>`;
    })
    .join("\n\n");
}

function renderLegalBody(localeKey, localeContent, pageType, pageContent) {
  const noteMarkup = pageContent.note
    ? `\n      <p class="legal-note">${pageContent.note}</p>`
    : "";

  return `${renderLegalHeader(localeKey, localeContent.nav, pageType)}

    <main class="legal-content">
      <div class="legal-title">
        <h1>${pageContent.heading}</h1>
        <p class="legal-updated">${pageContent.updatedLabel}</p>
      </div>

${renderLegalSections(pageContent.sections)}${noteMarkup}
    </main>
  </div>`;
}

function renderHomepage(localeKey, localeContent) {
  return pageShell({
    htmlLang: localeContent.htmlLang,
    head: renderHomepageHead(localeContent, localeKey),
    body: renderHomepageBody(localeKey, localeContent),
  });
}

function renderLegalPage(localeKey, localeContent, pageType, pageContent) {
  return pageShell({
    htmlLang: localeKey,
    head: renderLegalHead(localeKey, localeContent, pageContent),
    body: renderLegalBody(localeKey, localeContent, pageType, pageContent),
  });
}

function localeKeyFromContent(localeContent) {
  return localeContent.htmlLang || "en";
}

module.exports = {
  renderHomepage,
  renderLegalPage,
};
