const { SHARED } = require("./content");

function json(value) {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function pageShell({ htmlLang, head, body }) {
  return `<!doctype html>
<!-- Generated by scripts/generate.js. Do not edit manually. -->
<html lang="${htmlLang}">

<head>
${head}
</head>

<body>
${body}
</body>

</html>
`;
}

function renderMetaTags({
  title,
  description,
  canonical,
  locale,
  alternateLocale,
  ogImageAlt,
}) {
  return `  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="description" content="${description}" />
  <meta name="author" content="${SHARED.organizationName}" />
  <meta name="robots" content="index, follow" />
  <meta name="theme-color" content="#f7f7f5" />
  <meta name="color-scheme" content="light" />
  <title>${title}</title>
  <link rel="canonical" href="${canonical}" />
  <link rel="alternate" hreflang="en" href="${SHARED.siteUrl}/en/" />
  <link rel="alternate" hreflang="de" href="${SHARED.siteUrl}/de/" />
  <link rel="alternate" hreflang="x-default" href="${SHARED.siteUrl}/en/" />
  <meta property="og:title" content="${title}" />
  <meta property="og:description" content="${description}" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${canonical}" />
  <meta property="og:image" content="${SHARED.logoUrl}" />
  <meta property="og:image:alt" content="${ogImageAlt}" />
  <meta property="og:site_name" content="Paluv" />
  <meta property="og:locale" content="${locale}" />
  <meta property="og:locale:alternate" content="${alternateLocale}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${title}" />
  <meta name="twitter:description" content="${description}" />
  <meta name="twitter:image" content="${SHARED.logoUrl}" />
  <meta name="twitter:image:alt" content="${ogImageAlt}" />
  <link rel="icon" href="/assets/paluvico.ico" type="image/x-icon" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="${SHARED.fontsHref}" rel="stylesheet" />
  <link rel="stylesheet" href="/css/styles.css?v=${SHARED.assetVersion}" />
  <script defer src="${SHARED.analyticsScript}"></script>`;
}

function renderHomepageHead(localeContent, localeKey) {
  const canonical = `${SHARED.siteUrl}/${localeKey}/`;
  const graph = [
    {
      "@type": "Organization",
      "@id": `${SHARED.siteUrl}/#org`,
      name: SHARED.organizationName,
      url: `${SHARED.siteUrl}/`,
      logo: SHARED.logoUrl,
      email: [SHARED.generalEmail, SHARED.businessEmail],
      contactPoint: [
        {
          "@type": "ContactPoint",
          email: SHARED.generalEmail,
          contactType: "general",
        },
        {
          "@type": "ContactPoint",
          email: SHARED.businessEmail,
          contactType: "business",
        },
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SHARED.siteUrl}/#website`,
      url: canonical,
      name: SHARED.organizationName,
      publisher: { "@id": `${SHARED.siteUrl}/#org` },
      inLanguage: localeContent.htmlLang,
    },
  ];

  return `${renderMetaTags({
    title: localeContent.title,
    description: localeContent.description,
    canonical,
    locale: localeContent.locale,
    alternateLocale: localeContent.alternateLocale,
    ogImageAlt: localeContent.ogImageAlt,
  })}
  <script type="application/ld+json">
${indent(json({ "@context": "https://schema.org", "@graph": graph }), 4)}
  </script>`;
}

function renderLegalHead(localeKey, localeContent, pageContent) {
  const canonical = `${SHARED.siteUrl}${pageContent.path}`;
  const alternate = `${SHARED.siteUrl}${pageContent.alternatePath}`;
  const xDefault = localeKey === "en" ? canonical : alternate;

  return `  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="description" content="${pageContent.metaDescription}" />
  <meta name="robots" content="index, follow" />
  <meta name="theme-color" content="#f7f7f5" />
  <title>${pageContent.pageTitle}</title>
  <link rel="canonical" href="${canonical}" />
  <link rel="alternate" hreflang="${localeKey}" href="${canonical}" />
  <link rel="alternate" hreflang="${localeKey === "en" ? "de" : "en"}" href="${alternate}" />
  <link rel="alternate" hreflang="x-default" href="${xDefault}" />
  <link rel="icon" href="/assets/paluvico.ico" type="image/x-icon" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="${SHARED.fontsHref}" rel="stylesheet" />
  <link rel="stylesheet" href="/css/styles.css?v=${SHARED.assetVersion}" />`;
}

function renderHeader(localeKey, localeContent) {
  const enHomePath = "/en/";
  const deHomePath = "/de/";

  return `  <header class="site-header" data-no-blend-mobile>
      <a class="brand" href="#top">
        <img class="brand-logo" src="/assets/paluvlogo.png" alt="Paluv" />
      </a>
      <nav class="site-nav" id="site-nav">
        <a href="#top">${localeContent.nav.home}</a>
        <a href="#partners">${localeContent.nav.partners}</a>
        <a href="#products">${localeContent.nav.products}</a>
        <a href="#services">${localeContent.nav.services}</a>
        <a href="#contact">${localeContent.nav.contact}</a>
      </nav>
      <div class="header-actions">
        <div class="language-switch" aria-label="${localeContent.nav.languageSwitch}">
          <a href="${enHomePath}" lang="en" hreflang="en"${localeKey === "en" ? ' aria-current="page"' : ""}>EN</a>
          <span aria-hidden="true">/</span>
          <a href="${deHomePath}" lang="de" hreflang="de"${localeKey === "de" ? ' aria-current="page"' : ""}>DE</a>
        </div>
        <button class="nav-toggle" type="button" aria-controls="site-nav" aria-expanded="false">
          ${localeContent.nav.menu}
        </button>
      </div>
    </header>`;
}

function renderHero(localeContent) {
  const metaMarkup = localeContent.hero.meta
    .map(
      (item) => `            <div>
              <dt>${item.label}</dt>
              <dd>${item.value}</dd>
            </div>`
    )
    .join("\n");

  return `      <section class="hero" id="top">
        <div class="hero-frame" aria-hidden="true">
          <div class="hero-model" id="hero-model"></div>
        </div>
        <div class="hero-copy no-blend">
          <p class="eyebrow">${localeContent.hero.eyebrow}</p>
          <h1 class="hero-title contrast-split">${localeContent.hero.title}</h1>
          <p class="hero-subtitle">
            ${localeContent.hero.subtitle}
          </p>
          <div class="hero-actions">
            <a class="button no-blend" href="#contact" style="color: white;">${localeContent.hero.primaryCta}</a>
            <a class="button ghost" href="#partners">${localeContent.hero.secondaryCta}</a>
          </div>
          <dl class="hero-meta">
${metaMarkup}
          </dl>
        </div>
      </section>`;
}

function renderProductCards(items) {
  return items
    .map(
      (item) => `          <article class="card reveal">
            <div class="card-media">
              <img src="${item.image}" alt="${item.imageAlt}" />
            </div>
            <h3>${item.title}</h3>
            <p>${item.description}</p>
            <span class="card-tag">${item.tag}</span>
            <a class="button ghost card-cta" href="${item.href}">${item.cta}</a>
          </article>`
    )
    .join("\n");
}

function renderServiceCards(items) {
  return items
    .map(
      (item) => `          <article class="card reveal">
            <span class="card-index">${item.index}</span>
            <h3>${item.title}</h3>
            <p>${item.description}</p>
            <span class="card-tag">${item.tag}</span>
          </article>`
    )
    .join("\n");
}

function renderPartnerLogo(item) {
  if (item.logo) {
    return `<span class="partner-logo partner-logo--image">
                    <img src="${item.logo}" alt="${item.logoAlt || item.name}" />
                  </span>`;
  }

  return `<span class="partner-logo" aria-hidden="true">${item.logoText}</span>`;
}

function renderPartnersSection(localeContent) {
  const items = localeContent.partners.items
    .map((item) => {
      const detailId = `partner-detail-${item.id}`;
      const optionalLink = item.href
        ? `              <a class="partner-detail__link" href="${item.href}">${item.cta || item.href}</a>\n`
        : "";

      return `          <article class="partner-card reveal" data-partner-card>
            <button class="partner-card__button no-blend" type="button" aria-expanded="false" aria-controls="${detailId}">
              <span class="partner-card__status">${item.status}</span>
              <span class="partner-card__identity">
                ${renderPartnerLogo(item)}
                <span class="partner-card__copy">
                  <span class="partner-card__name">${item.name}</span>
                  <span class="partner-card__category">${item.category}</span>
                </span>
              </span>
              <span class="partner-card__hint">${localeContent.partners.interactionHint}</span>
            </button>
            <div class="partner-detail" id="${detailId}" role="region" aria-label="${item.name} ${localeContent.partners.detailLabel}">
              <span>${localeContent.partners.detailLabel}</span>
              <p>${item.services}</p>
              <small>${item.note}</small>
${optionalLink}            </div>
          </article>`;
    })
    .join("\n");

  return `      <section class="section partners-section no-blend" id="partners" aria-labelledby="partners-title">
        <div class="partners-header">
          <div class="section-title section-title--wide">
            <p class="eyebrow">${localeContent.partners.kicker}</p>
            <h2 id="partners-title">${localeContent.sections.partners.title}</h2>
            <p>${localeContent.sections.partners.subtitle}</p>
          </div>
          <div class="partners-note">
            <span>${localeContent.partners.summary}</span>
          </div>
        </div>
        <div class="partners-grid">
${items}
        </div>
      </section>`;
}

function renderTrustLogo(item) {
  return `              <span class="trust-logo">
                <img src="${item.logo}" alt="${item.alt || item.name}" />
              </span>`;
}

function renderTrustSection(localeContent) {
  const groups = localeContent.trust.groups
    .map((group) => {
      const logos = group.items.map(renderTrustLogo).join("\n");

      return `          <article class="trust-group reveal">
            <p>${group.label}</p>
            <div class="trust-logos">
${logos}
            </div>
          </article>`;
    })
    .join("\n");

  return `      <section class="section trust-section no-blend" id="trust" aria-labelledby="trust-title">
        <div class="section-title section-title--wide">
          <p class="eyebrow">${localeContent.trust.kicker}</p>
          <h2 id="trust-title">${localeContent.trust.title}</h2>
          <p>${localeContent.trust.subtitle}</p>
        </div>
        <div class="trust-grid">
${groups}
        </div>
      </section>`;
}

function renderProductsSection(localeContent) {
  return `      <section class="section" id="products">
        <div class="section-title">
          <h2>${localeContent.sections.products.title}</h2>
        </div>
        <div class="grid products-grid">
${renderProductCards(localeContent.products)}
        </div>
      </section>`;
}

function renderServicesSection(localeContent) {
  return `      <section class="section" id="services">
        <div class="section-title">
          <h2>${localeContent.sections.services.title}</h2>
          <p>${localeContent.sections.services.subtitle}</p>
        </div>
        <div class="grid services-grid">
${renderServiceCards(localeContent.services)}
        </div>
      </section>`;
}

function renderHomepageBody(localeKey, localeContent) {
  return `  <div class="viewport-shell" aria-hidden="true">
    <div id="engine-background"></div>
  </div>
  <div id="model-preloader" class="model-preloader no-blend" aria-live="polite" aria-busy="true"
    data-loading-text="${localeContent.loadingText}" data-error-text="${localeContent.loadingErrorText}">
    <div class="model-preloader__spinner" role="img" aria-label="${localeContent.loadingAriaLabel}"></div>
    <span class="model-preloader__label">${localeContent.loadingText}</span>
  </div>
  <div class="page blend-text">
${renderHeader(localeKey, localeContent)}

    <main>
${renderHero(localeContent)}

${renderPartnersSection(localeContent)}

${renderTrustSection(localeContent)}

${renderProductsSection(localeContent)}

${renderServicesSection(localeContent)}
    </main>

    <footer class="site-footer" id="contact">
      <div class="contact-header">
        <h2>${localeContent.contact.title}</h2>
      </div>
      <div class="contact-grid">
        <form class="contact-form" id="contact-form">
          <label>
            <span>${localeContent.contact.fields.name}</span>
            <input type="text" name="name" placeholder="${localeContent.contact.placeholders.name}" autocomplete="name" required />
          </label>
          <label>
            <span>${localeContent.contact.fields.email}</span>
            <input type="email" name="email" placeholder="${localeContent.contact.placeholders.email}" autocomplete="email" required />
          </label>
          <label>
            <span>${localeContent.contact.fields.message}</span>
            <textarea name="message" rows="4" placeholder="${localeContent.contact.placeholders.message}" required></textarea>
          </label>
          <button class="button no-blend" type="submit">${localeContent.contact.submit}</button>
          <p class="form-status" id="form-status" role="status" aria-live="polite"></p>
        </form>
        <div class="contact-map">
          <iframe class="map-embed" title="${localeContent.map.title}" loading="lazy"
            src="${SHARED.mapEmbedSrc}"></iframe>
          <p class="map-caption">
            ${localeContent.map.caption}
          </p>
        </div>
      </div>
      <div class="footer-meta">
        <span>${SHARED.organizationName}</span>
        <span>© ${SHARED.year}</span>
        <span>${SHARED.generalEmail} · ${SHARED.businessEmail}</span>
        <span class="footer-links">
          <a href="${localeKey === "en" ? "/en/imprint/" : "/de/impressum/"}">${localeContent.footer.imprint}</a>
          <a href="${localeKey === "en" ? "/en/privacy/" : "/de/datenschutz/"}">${localeContent.footer.privacy}</a>
        </span>
      </div>
    </footer>
  </div>

  <script src="/js/hero-loader.js" defer></script>
  <script type="importmap">
      {
        "imports": {
          "three": "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js",
          "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/"
        }
      }
    </script>
  <script type="module" src="/js/hero-main.js"></script>
  <script src="/js/scripts.js?v=${SHARED.assetVersion}" defer></script>`;
}

function renderLegalHeader(localeKey, nav, pageType) {
  const homePath = localeKey === "en" ? "/en/" : "/de/";
  const pagePath =
    pageType === "imprint"
      ? localeKey === "en"
        ? "/en/imprint/"
        : "/de/impressum/"
      : localeKey === "en"
        ? "/en/privacy/"
        : "/de/datenschutz/";
  const otherPath =
    pageType === "imprint"
      ? localeKey === "en"
        ? "/de/impressum/"
        : "/en/imprint/"
      : localeKey === "en"
        ? "/de/datenschutz/"
        : "/en/privacy/";

  return `  <div class="page legal-page">
    <header class="site-header legal-header no-blend">
      <a class="brand" href="${homePath}">
        <img class="brand-logo" src="/assets/paluvlogo.png" alt="Paluv" />
      </a>
      <nav class="site-nav legal-nav">
        <a href="${homePath}">${nav.home}</a>
        <a href="${localeKey === "en" ? "/en/imprint/" : "/de/impressum/"}"${pageType === "imprint" ? ' aria-current="page"' : ""}>${nav.imprint}</a>
        <a href="${localeKey === "en" ? "/en/privacy/" : "/de/datenschutz/"}"${pageType === "privacy" ? ' aria-current="page"' : ""}>${nav.privacy}</a>
      </nav>
      <div class="header-actions">
        <div class="language-switch" aria-label="${nav.languageSwitch}">
          <a href="${localeKey === "en" ? pagePath : otherPath}" lang="en" hreflang="en"${localeKey === "en" ? ' aria-current="page"' : ""}>EN</a>
          <span aria-hidden="true">/</span>
          <a href="${localeKey === "de" ? pagePath : otherPath}" lang="de" hreflang="de"${localeKey === "de" ? ' aria-current="page"' : ""}>DE</a>
        </div>
      </div>
    </header>`;
}

function renderLegalSections(sections) {
  return sections
    .map((section) => {
      const paragraphs = section.paragraphs
        .map((paragraph) => `        <p>${paragraph}</p>`)
        .join("\n");
      return `      <section>
        <h2>${section.title}</h2>
${paragraphs}
      </section>`;
    })
    .join("\n\n");
}

function renderLegalBody(localeKey, localeContent, pageType, pageContent) {
  const noteMarkup = pageContent.note
    ? `\n      <p class="legal-note">${pageContent.note}</p>`
    : "";

  return `${renderLegalHeader(localeKey, localeContent.nav, pageType)}

    <main class="legal-content">
      <h1>${pageContent.heading}</h1>
      <p class="legal-updated">${pageContent.updatedLabel}</p>

${renderLegalSections(pageContent.sections)}${noteMarkup}
    </main>
  </div>`;
}

function renderHomepage(localeKey, localeContent) {
  return pageShell({
    htmlLang: localeContent.htmlLang,
    head: renderHomepageHead(localeContent, localeKey),
    body: renderHomepageBody(localeKey, localeContent),
  });
}

function renderLegalPage(localeKey, localeContent, pageType, pageContent) {
  return pageShell({
    htmlLang: localeKey,
    head: renderLegalHead(localeKey, localeContent, pageContent),
    body: renderLegalBody(localeKey, localeContent, pageType, pageContent),
  });
}

function indent(value, count) {
  const prefix = " ".repeat(count);
  return value
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n");
}

module.exports = {
  renderHomepage,
  renderLegalPage,
};
